
require 'active_support/inflector'
require 'colorize'
require 'json'
require 'pry'
require 'rexml/document'
require 'singleton'

require_relative 'patch/string_patch'
require_relative 'patch/symbol_patch'

require_relative 'tools/report'
require_relative 'tools/tibet_console'
require_relative 'tools/tibet_controller'
require_relative 'tools/tibet_provider'

require_relative 'graph/graph_element'
require_relative 'graph/vertex'
require_relative 'graph/arc'
require_relative 'graph/graph'
require_relative 'graph/parser'
require_relative 'graph/graph_builder'
require_relative 'graph/graph_provider'

require_relative 'model/model_provider'
require_relative 'model/model_element'
require_relative 'model/model'

require_relative 'model/overlay/model_overlay'

require_relative 'model/construction/model_builder'
require_relative 'model/construction/graph_based_builder'

require_relative 'model/node/support/marker_support'
require_relative 'model/node/type/derived/derived_type_support'
require_relative 'model/node/support/inheritance_support'
require_relative 'model/node/support/node_predicate_support'
require_relative 'model/node/support/edge_inheritance_proxy'
require_relative 'model/node/node'
require_relative 'model/node/actual_node'
require_relative 'model/node/type/actual/type_node'
require_relative 'model/node/attribute/attribute'
require_relative 'model/node/attribute/virtual_attribute'

require_relative 'model/edge/support/virtual_edge_support'
require_relative 'model/edge/support/edge_multiplicity_support'
require_relative 'model/edge/support/edge_modifier_support'
require_relative 'model/edge/support/edge_predicate_support'
require_relative 'model/edge/support/hyper_edge_support'
require_relative 'model/edge/edge'
require_relative 'model/edge/semantic_edge'
require_relative 'model/edge/connector_edge'
require_relative 'model/edge/supply_edge'
require_relative 'model/edge/attribution_edge'
require_relative 'model/edge/virtual/virtual_attribution_edge'
require_relative 'model/edge/virtual/virtual_supply_edge'
require_relative 'model/edge/association/association'
require_relative 'model/edge/association/many_to_one_association'
require_relative 'model/edge/association/many_to_many_association'
require_relative 'model/edge/aggregation/aggregation'
require_relative 'model/edge/composition/composition'

require_relative 'model/node/constraint/specific_constraint'
require_relative 'model/node/constraint/inclusion_constraint'
require_relative 'model/node/constraint/exclusion_constraint'
require_relative 'model/node/constraint/format_constraint'
require_relative 'model/node/constraint/interval_constraint'

require_relative 'model/construction/refinements/element_refinement'

require_relative 'model/construction/refinements/10/arc/arc_refinement'
require_relative 'model/construction/refinements/10/vertex/vertex_refinement'
require_relative 'model/construction/refinements/10/vertex/entity_type_refinement'
require_relative 'model/construction/refinements/10/vertex/query_type_refinement'
require_relative 'model/construction/refinements/10/vertex/relationship_type_refinement'
require_relative 'model/construction/refinements/10/vertex/enumeration_type_refinement'
require_relative 'model/construction/refinements/10/vertex/attribute_refinement'
require_relative 'model/construction/refinements/10/vertex/class_type_refinement'
require_relative 'model/construction/refinements/10/vertex/module_type_refinement'
require_relative 'model/construction/refinements/10/vertex/edge_connector_refinement'
require_relative 'model/construction/refinements/10/vertex/constraint_refinement'
require_relative 'model/construction/refinements/10/arc/association_refinement'
require_relative 'model/construction/refinements/10/arc/aggregation_refinement'
require_relative 'model/construction/refinements/10/arc/composition_refinement'
require_relative 'model/construction/refinements/10/arc/attribution_edge_refinement'
require_relative 'model/construction/refinements/10/arc/restriction_edge_refinement'
require_relative 'model/construction/refinements/10/arc/classification_edge_refinement'
require_relative 'model/construction/refinements/10/arc/inclusion_edge_refinement'
require_relative 'model/construction/refinements/10/arc/connector_edge_refinement'
require_relative 'model/construction/refinements/10/arc/semantic_edge_refinement'
require_relative 'model/construction/refinements/10/arc/supply_edge_refinement'

require_relative 'model/construction/refinements/20/visual_position_calculation_refinement'
require_relative 'model/construction/refinements/20/edge_connector_on_derived_arc_refinement'

require_relative 'model/construction/refinements/30/hide_tentative_refinement'
require_relative 'model/construction/refinements/30/enumeration_attribute_2_enumeration_type_refinement'
require_relative 'model/construction/refinements/30/association/one_to_one_association_refinement'
require_relative 'model/construction/refinements/30/association/one_to_many_association_refinement'
require_relative 'model/construction/refinements/30/association/many_to_one_association_refinement'
require_relative 'model/construction/refinements/30/association/many_to_many_association_refinement'
require_relative 'model/construction/refinements/30/aggregation/one_to_one_aggregation_refinement'
require_relative 'model/construction/refinements/30/aggregation/one_to_many_aggregation_refinement'
require_relative 'model/construction/refinements/30/aggregation/many_to_one_aggregation_refinement'
require_relative 'model/construction/refinements/30/aggregation/many_to_many_aggregation_refinement'
require_relative 'model/construction/refinements/30/composition/one_to_one_composition_refinement'
require_relative 'model/construction/refinements/30/composition/one_to_many_composition_refinement'
require_relative 'model/construction/refinements/30/constraint_specialization_refinement'
require_relative 'model/construction/refinements/30/enumeration_type_normalization_refinement'

require_relative 'model/construction/refinements/40/type_unification_refinement'
require_relative 'model/construction/refinements/40/m2n_bi_polymorphic_join_model_decomposition_refinement'
require_relative 'model/construction/refinements/40/transitive_association_detection_refinement'
require_relative 'model/construction/refinements/40/polymorphic_association_detection_refinement'
require_relative 'model/construction/refinements/40/reflexive_association_detection_refinement'

require_relative 'model/tibet_model_view'

require_relative 'model/construction/syntax/node_syntax'
require_relative 'model/construction/syntax/edge_syntax'
require_relative 'model/construction/syntax/syntax_checker'

require_relative 'model/edge/classification_edge'
require_relative 'model/edge/inclusion_edge'
require_relative 'model/edge/restriction_edge'

require_relative 'model/node/type/actual/class_type'
require_relative 'model/node/type/actual/module_type'
require_relative 'model/node/constraint/constraint'
require_relative 'model/node/edge_connector'
require_relative 'model/node/type/actual/entity_type'
require_relative 'model/node/type/actual/query_type'
require_relative 'model/node/type/actual/enumeration_type'
require_relative 'model/node/type/virtual/virtual_entity_type'
# require_relative 'model/node/type/virtual/virtual_enumeration_type'
require_relative 'model/node/type/actual/relationship_type'

require_relative 'graph/derived_arc'

require_relative 'model/edge/association/many_to_many_association'
require_relative 'model/edge/association/many_to_one_association'
require_relative 'model/edge/association/one_to_many_association'
require_relative 'model/edge/association/one_to_one_association'
require_relative 'model/edge/aggregation/many_to_many_aggregation'
require_relative 'model/edge/aggregation/many_to_one_aggregation'
require_relative 'model/edge/aggregation/one_to_many_aggregation'
require_relative 'model/edge/aggregation/one_to_one_aggregation'
require_relative 'model/edge/composition/one_to_many_composition'
require_relative 'model/edge/composition/one_to_one_composition'
require_relative 'model/edge/aggregation/virtual/virtual_many_to_one_aggregation'
require_relative 'model/edge/aggregation/virtual/virtual_many_to_many_aggregation'

require_relative 'model/edge/association/virtual/virtual_one_to_many_association'
require_relative 'model/edge/aggregation/virtual/virtual_one_to_many_aggregation'
require_relative 'model/edge/composition/virtual/virtual_one_to_many_composition'

require_relative 'model/edge/association/virtual/virtual_many_to_one_association'
require_relative 'model/edge/aggregation/virtual/virtual_many_to_one_aggregation'

require_relative 'model/overlay/polymorphic_association'
require_relative 'model/overlay/reflexive_association'
require_relative 'model/overlay/transitive_association'

require_relative 'model/node/type/derived/derived_class_type'
require_relative 'model/node/type/derived/derived_module_type'
require_relative 'model/node/type/derived/derived_entity_type'
require_relative 'model/node/type/derived/derived_enumeration_type'
require_relative 'model/node/type/derived/derived_query_type'
require_relative 'model/node/type/derived/derived_relationship_type'

require_relative 'model/edge/aggregation/many_to_many_aggregation'
require_relative 'model/edge/aggregation/many_to_one_aggregation'
require_relative 'model/edge/aggregation/one_to_many_aggregation'
require_relative 'model/edge/aggregation/one_to_one_aggregation'
require_relative 'model/edge/association/many_to_many_association'
require_relative 'model/edge/association/many_to_one_association'
require_relative 'model/edge/association/one_to_many_association'
require_relative 'model/edge/association/one_to_one_association'
require_relative 'model/edge/composition/one_to_many_composition'
require_relative 'model/edge/composition/one_to_one_composition'

require_relative 'model/endpoint'

# require_relative 'test-/simple_test-'